import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../provider";
import UserProfile from "../modules/user/components/user-profile";
import Nav from "../modules/common/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex flex-col items-stretch h-screen bg-slate-950 text-slate-300"
        }
      >
        <Providers>
          <header className="h-16 w-full flex-none border-b border-slate-500 py-2 px-4 flex justify-between items-center">
            <UserProfile />
          </header>
          <main className="flex-auto flex items-stretch">
            <Nav />
            <section className="flex-auto">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
